BEGIN;

ALTER TABLE public.productos_mesa
    DROP CONSTRAINT IF EXISTS productos_mesa_pkey;

ALTER TABLE public.productos_mesa
    ADD COLUMN IF NOT EXISTS id_pedido_producto INT4 GENERATED BY DEFAULT AS IDENTITY;

UPDATE public.productos_mesa
SET id_pedido_producto = DEFAULT
WHERE id_pedido_producto IS NULL;

ALTER TABLE public.productos_mesa
    ALTER COLUMN id_pedido_producto SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'productos_mesa_pkey'
          AND conrelid = 'public.productos_mesa'::regclass
    ) THEN
        ALTER TABLE public.productos_mesa
            ADD CONSTRAINT productos_mesa_pkey PRIMARY KEY (id_pedido_producto);
    END IF;
END $$;

ALTER TABLE public.productos_mesa
    ADD COLUMN IF NOT EXISTS creado_at TIMESTAMP;

UPDATE public.productos_mesa
SET creado_at = COALESCE(creado_at, CURRENT_TIMESTAMP)
WHERE creado_at IS NULL;

ALTER TABLE public.productos_mesa
    ALTER COLUMN creado_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.productos_mesa
    ALTER COLUMN creado_at SET NOT NULL;

ALTER TABLE public.productos_mesa
    ADD COLUMN IF NOT EXISTS venta_id INT4 NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_productos_mesa_venta'
          AND conrelid = 'public.productos_mesa'::regclass
    ) THEN
        ALTER TABLE public.productos_mesa
            ADD CONSTRAINT fk_productos_mesa_venta
            FOREIGN KEY (venta_id)
            REFERENCES public.venta (id_venta)
            ON UPDATE CASCADE
            ON DELETE SET NULL;
    END IF;
END $$;

SELECT setval(
    pg_get_serial_sequence('public.productos_mesa', 'id_pedido_producto'),
    COALESCE((SELECT MAX(id_pedido_producto) FROM public.productos_mesa), 1),
    true
);

COMMIT;