package com.diep.coffeeguin_backend.dao;

import com.diep.coffeeguin_backend.db.DBConnection;
import com.diep.coffeeguin_backend.model.Categoria;
import org.springframework.stereotype.Repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

@Repository
public class CategoriaDAOImpl implements CategoriaDAO {

	private final DBConnection dbConnection;

	public CategoriaDAOImpl(DBConnection dbConnection) {
		this.dbConnection = dbConnection;
		crearTablaSiNoExiste();
	}

	@Override
	public void agregar(Categoria categoria) {
		String sql = "INSERT INTO categoria (nombre) VALUES (?)";
		try (Connection connection = dbConnection.getConnection();
			 PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
			statement.setString(1, categoria.getNombre());
			statement.executeUpdate();
			try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
				if (generatedKeys.next()) {
					categoria.setId(generatedKeys.getLong(1));
				}
			}
		} catch (SQLException exception) {
			throw new IllegalStateException("No se pudo registrar la categoria", exception);
		}
	}

	@Override
	public void eliminar(Categoria categoria) {
		String sql = "DELETE FROM categoria WHERE id = ?";
		try (Connection connection = dbConnection.getConnection();
			 PreparedStatement statement = connection.prepareStatement(sql)) {
			statement.setLong(1, categoria.getId());
			statement.executeUpdate();
		} catch (SQLException exception) {
			throw new IllegalStateException("No se pudo eliminar la categoria", exception);
		}
	}

	@Override
	public Categoria buscarPorId(int id) {
		String sql = "SELECT id, nombre FROM categoria WHERE id = ?";
		try (Connection connection = dbConnection.getConnection();
			 PreparedStatement statement = connection.prepareStatement(sql)) {
			statement.setInt(1, id);
			try (ResultSet resultSet = statement.executeQuery()) {
				if (!resultSet.next()) {
					return null;
				}

				Categoria categoria = new Categoria();
				categoria.setId(resultSet.getLong("id"));
				categoria.setNombre(resultSet.getString("nombre"));
				return categoria;
			}
		} catch (SQLException exception) {
			throw new IllegalStateException("No se pudo buscar la categoria", exception);
		}
	}

	@Override
	public List<Categoria> listarTodos() {
		String sql = "SELECT id, nombre FROM categoria ORDER BY id";
		List<Categoria> categorias = new ArrayList<>();
		try (Connection connection = dbConnection.getConnection();
			 PreparedStatement statement = connection.prepareStatement(sql);
			 ResultSet resultSet = statement.executeQuery()) {
			while (resultSet.next()) {
				Categoria categoria = new Categoria();
				categoria.setId(resultSet.getLong("id"));
				categoria.setNombre(resultSet.getString("nombre"));
				categorias.add(categoria);
			}
			return categorias;
		} catch (SQLException exception) {
			throw new IllegalStateException("No se pudo listar las categorias", exception);
		}
	}

	@Override
	public void actualizar(Categoria categoria) {
		String sql = "UPDATE categoria SET nombre = ? WHERE id = ?";
		try (Connection connection = dbConnection.getConnection();
			 PreparedStatement statement = connection.prepareStatement(sql)) {
			statement.setString(1, categoria.getNombre());
			statement.setLong(2, categoria.getId());
			statement.executeUpdate();
		} catch (SQLException exception) {
			throw new IllegalStateException("No se pudo actualizar la categoria", exception);
		}
	}

	private void crearTablaSiNoExiste() {
		String sql = "CREATE TABLE IF NOT EXISTS categoria ("
			+ "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
			+ "nombre VARCHAR(150) NOT NULL"
			+ ")";
		try (Connection connection = dbConnection.getConnection();
			 Statement statement = connection.createStatement()) {
			statement.execute(sql);
		} catch (SQLException exception) {
			throw new IllegalStateException("No se pudo preparar la tabla de categoria", exception);
		}
	}
}